# Generated by Django 4.2.7 on 2025-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('auto', 'Auto (System)'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10),
        ),
    ]
