# Generated by Django 4.2.7 on 2025-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='dark', max_length=10),
        ),
    ]
