# Generated by Django 4.2.7 on 2025-07-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
