# Generated by Django 4.2.7 on 2025-07-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_userprofile_theme_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='theme_preference',
            new_name='theme',
        ),
    ]
