# Generated by Django 4.2.7 on 2025-07-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_finetunedmodel_modelperformancemetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_interests', models.JSONField(default=list)),
                ('study_preferences', models.JSONField(default=dict)),
                ('program_level_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range', models.JSONField(blank=True, null=True)),
                ('location_preferences', models.JSONField(default=list)),
                ('academic_background', models.JSONField(default=dict)),
                ('last_discussed_programs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Conversation Memories',
                'db_table': 'chatbot_conversation_memory',
            },
        ),
        migrations.CreateModel(
            name='ProgramRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('relevance_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('matching_criteria', models.JSONField(default=list)),
                ('user_feedback', models.JSONField(blank=True, null=True)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chatbot_program_recommendation',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.AlterModelOptions(
            name='knowledgebaseentry',
            options={'verbose_name_plural': 'Knowledge Base Entries'},
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseentry',
            name='chatbot_kno_dataset_9c8413_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseentry',
            name='chatbot_kno_categor_2a86ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgebaseentry',
            name='chatbot_kno_confide_d7e9a2_idx',
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='confidence_score',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.trainingdataset'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='entry_type',
            field=models.CharField(choices=[('general', 'General Information'), ('program', 'Program Information'), ('accommodation', 'Accommodation Information'), ('module', 'Module Information'), ('fee', 'Fee Information'), ('admission', 'Admission Requirements'), ('facility', 'Campus Facility')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='question',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['category'], name='chatbot_kno_categor_b37a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['entry_type'], name='chatbot_kno_entry_t_e52aac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['is_validated'], name='chatbot_kno_is_vali_70e24c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['is_deleted'], name='chatbot_kno_is_dele_b866ac_idx'),
        ),
        migrations.AlterModelTable(
            name='knowledgebaseentry',
            table=None,
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot.conversation'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='program',
            field=models.ForeignKey(limit_choices_to={'entry_type': 'program'}, on_delete=django.db.models.deletion.CASCADE, to='chatbot.knowledgebaseentry'),
        ),
        migrations.AddField(
            model_name='conversationmemory',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='chatbot.conversation'),
        ),
        migrations.AddIndex(
            model_name='programrecommendation',
            index=models.Index(fields=['conversation', '-relevance_score'], name='chatbot_pro_convers_c85947_idx'),
        ),
        migrations.AddIndex(
            model_name='programrecommendation',
            index=models.Index(fields=['relevance_level'], name='chatbot_pro_relevan_d33016_idx'),
        ),
    ]
