# Generated by Django 4.2.7 on 2025-07-17 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0013_add_memory_strategy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='programrecommendation',
            name='chatbot_pro_convers_c85947_idx',
        ),
        migrations.RemoveIndex(
            model_name='programrecommendation',
            name='chatbot_pro_relevan_d33016_idx',
        ),
        migrations.RenameField(
            model_name='programrecommendation',
            old_name='recommended_at',
            new_name='created_at',
        ),
        migrations.RenameIndex(
            model_name='conversationmemory',
            new_name='chatbot_con_convers_00d36e_idx',
            old_name='chatbot_conversationmemory_conversation_id_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmemory',
            new_name='chatbot_con_user_id_a9689c_idx',
            old_name='chatbot_conversationmemory_user_memory_type_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmemory',
            new_name='chatbot_con_memory__476268_idx',
            old_name='chatbot_conversationmemory_strategy_active_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmemory',
            new_name='chatbot_con_is_acti_d3f466_idx',
            old_name='chatbot_conversationmemory_active_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmemory',
            new_name='chatbot_con_expires_8f986c_idx',
            old_name='chatbot_conversationmemory_expires_at_idx',
        ),
        migrations.RemoveField(
            model_name='programrecommendation',
            name='matching_criteria',
        ),
        migrations.RemoveField(
            model_name='programrecommendation',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programrecommendation',
            name='relevance_level',
        ),
        migrations.RemoveField(
            model_name='programrecommendation',
            name='relevance_score',
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='confidence_score',
            field=models.FloatField(default=0.7, help_text='Confidence in recommendation quality'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='recommendation_reasoning',
            field=models.TextField(default='', help_text='Why these programs were recommended'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='recommended_programs',
            field=models.JSONField(default=dict, help_text='List of recommended programs with scores'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='selected_programs',
            field=models.JSONField(default=list, help_text='Programs user showed interest in'),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted by User'), ('rejected', 'Rejected by User'), ('applied', 'User Applied'), ('enrolled', 'User Enrolled')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programrecommendation',
            name='user_criteria',
            field=models.JSONField(default=dict, help_text='User criteria used for recommendation'),
        ),
        migrations.AlterField(
            model_name='programrecommendation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programrecommendation',
            name='user_feedback',
            field=models.TextField(blank=True, help_text='User feedback on recommendations'),
        ),
        migrations.AddIndex(
            model_name='programrecommendation',
            index=models.Index(fields=['user', '-created_at'], name='chatbot_pro_user_id_1060a0_idx'),
        ),
        migrations.AddIndex(
            model_name='programrecommendation',
            index=models.Index(fields=['status', '-created_at'], name='chatbot_pro_status_7caf0d_idx'),
        ),
    ]
